[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/orologo"
  to = "/.netlify/functions/orologo"
  status = 200

[[redirects]]
  from = "/api/verify"
  to = "/.netlify/functions/verify"
  status = 200
